{
 "title": "DRBD Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "drbd_device_role", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Out Of Sync Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "drbd_out_of_sync_bytes",
     "legendFormat": "{{instance}} >>> {{connection}}"
    }
   ]
  },
  {
   "title": "DRBD Disk Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(drbd_disk_written_bytes[10s])",
     "legendFormat": "{{instance}} >>> {{connection}} --- {{resource}}"
    }
   ]
  },
  {
   "title": "DRBD Unhealthy Connection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drbd_connection_unhealthy",
     "legendFormat": "{{instance}} >>> {{connection}}"
    }
   ]
  },
  {
   "title": "DRBD Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(drbd_disk_read_bytes[10s])",
     "legendFormat": "{{instance}} >>> {{connection}} --- {{resource}}"
    }
   ]
  },
  {
   "title": "DRBD Connection Established",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drbd_connection_established",
     "legendFormat": "{{instance}} >>> {{connection}}"
    }
   ]
  },
  {
   "title": "Network Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(drbd_network_sent_bytes[10s])",
     "legendFormat": "{{instance}} >>> {{connection}} --- {{resource}}"
    }
   ]
  },
  {
   "title": "Local Disk Up To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drbd_local_disk_up_to_date",
     "legendFormat": "{{instance}} >>> {{connection}}"
    }
   ]
  },
  {
   "title": "Network Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(drbd_network_received_bytes[10s])",
     "legendFormat": "{{instance}} >>> {{connection}} --- {{resource}}"
    }
   ]
  },
  {
   "title": "Not Responded Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "drbd_remote_unacknowledged",
     "legendFormat": "{{instance}} >>> {{connection}} --- {{resource}}"
    }
   ]
  },
  {
   "title": "Local Pending I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "drbd_local_pending", "legendFormat": "{{instance}} --- {{resource}}" }
   ]
  },
  {
   "title": "DRBD Activity Log Writes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "drbd_activitylog_writes", "legendFormat": "{{instance}} --- {{resource}}" }
   ]
  },
  {
   "title": "Number of Epochs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "drbd_epochs",
     "legendFormat": "{{instance}} >>> {{connection}} --- {{resource}}"
    }
   ]
  },
  {
   "title": "DRBD Bitmap Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    { "expr": "rate(drbd_bitmap_writes[10s])", "legendFormat": "{{instance}} --- {{resource}}" }
   ]
  }
 ]
}